# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.9
  hooks:
    - id: insert-license
      args: [--license-filepath, LICENSE]
      types: [python]
- repo: https://github.com/asottile/setup-cfg-fmt
  rev: v1.16.0
  hooks:
    - id: setup-cfg-fmt
- repo: https://github.com/PyCQA/isort
  rev: 5.7.0
  hooks:
    - id: isort
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: trailing-whitespace
    - id: mixed-line-ending
    - id: check-yaml
    - id: check-toml
    - id: check-merge-conflict
    - id: check-executables-have-shebangs
